name: "cachix"
on:
  pull_request:
  push:
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: fmcachix
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - env:
        TEST: 1
        # NIXPKGS_ALLOW_UNFREE: 1
      run: |
        nix build ./#custom.git --verbose
  xdman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: fmcachix
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - env:
        TEST: 1
        # NIXPKGS_ALLOW_UNFREE: 1
      # run: nix-build '<nixpkgs>' --attr mongodb
      run: |
        nix build ./#custom.xdman --verbose
